//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneClickInstallation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OneClickHomePageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OneClickHomePageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneClickInstallation.Resources.OneClickHomePageResource", typeof(OneClickHomePageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms and conditions of the Apache license.
        /// </summary>
        public static string AcceptTermsLinkText {
            get {
                return ResourceManager.GetString("AcceptTermsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by clicking this button you accept the.
        /// </summary>
        public static string AcceptTermsText {
            get {
                return ResourceManager.GetString("AcceptTermsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Server.
        /// </summary>
        public static string CommunityServer {
            get {
                return ResourceManager.GetString("CommunityServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLYOFFICE Community Server.
        /// </summary>
        public static string CommunityServerHdr {
            get {
                return ResourceManager.GetString("CommunityServerHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLYOFFICE Community Server is a collaborative system developed to manage documents, projects, customer relationship and email correspondence, all in one place..
        /// </summary>
        public static string CommunityServerText {
            get {
                return ResourceManager.GetString("CommunityServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string ConnectionErrorHdr {
            get {
                return ResourceManager.GetString("ConnectionErrorHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the server..
        /// </summary>
        public static string ConnectionErrorText_1 {
            get {
                return ResourceManager.GetString("ConnectionErrorText_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check connection setting and try again..
        /// </summary>
        public static string ConnectionErrorText_2 {
            get {
                return ResourceManager.GetString("ConnectionErrorText_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! Server connection established successfully..
        /// </summary>
        public static string ConnectionSettingsConnectedFormDescHdr {
            get {
                return ResourceManager.GetString("ConnectionSettingsConnectedFormDescHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect to a different server, you will need to disconnect first..
        /// </summary>
        public static string ConnectionSettingsConnectedFormDescText {
            get {
                return ResourceManager.GetString("ConnectionSettingsConnectedFormDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already connected to your server..
        /// </summary>
        public static string ConnectionSettingsConnectedFormText {
            get {
                return ResourceManager.GetString("ConnectionSettingsConnectedFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLYOFFICE One Click Installation.
        /// </summary>
        public static string ConnectionSettingsFormDescHdr {
            get {
                return ResourceManager.GetString("ConnectionSettingsFormDescHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ONLYOFFICE Installer used to automate the deployement process of ONLYOFFICE Free Edition using the Docker container technology.  ONLYOFFICE Free Edition is an open source software that comprises online document editors, collaboration system and mail server, all to resolve the collaboration issues for both small and medium-sized teams..
        /// </summary>
        public static string ConnectionSettingsFormDescText {
            get {
                return ResourceManager.GetString("ConnectionSettingsFormDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string ConnectionSettingsFormHdr {
            get {
                return ResourceManager.GetString("ConnectionSettingsFormHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you start the installation process, you need to connect to your server. Fill out the form below and click the &apos;CONNECT&apos; button..
        /// </summary>
        public static string ConnectionSettingsFormText {
            get {
                return ResourceManager.GetString("ConnectionSettingsFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect your server.
        /// </summary>
        public static string ConnectStepText {
            get {
                return ResourceManager.GetString("ConnectStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us at.
        /// </summary>
        public static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trail.
        /// </summary>
        public static string ContrrolPanelFeatureAudit {
            get {
                return ResourceManager.GetString("ContrrolPanelFeatureAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string ContrrolPanelFeatureBackup {
            get {
                return ResourceManager.GetString("ContrrolPanelFeatureBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTPS.
        /// </summary>
        public static string ContrrolPanelFeatureHttps {
            get {
                return ResourceManager.GetString("ContrrolPanelFeatureHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ContrrolPanelFeatureUpdate {
            get {
                return ResourceManager.GetString("ContrrolPanelFeatureUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ContrrolPanelHdr {
            get {
                return ResourceManager.GetString("ContrrolPanelHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLYOFFICE Control Panel is a new way to manage and configure your server in one click. It offers features like ....
        /// </summary>
        public static string ContrrolPanelText {
            get {
                return ResourceManager.GetString("ContrrolPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize settings*.
        /// </summary>
        public static string CustomStepText {
            get {
                return ResourceManager.GetString("CustomStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Advanced configuration settings provided on commercial basis.
        /// </summary>
        public static string CustomStepTitleText {
            get {
                return ResourceManager.GetString("CustomStepTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Server.
        /// </summary>
        public static string DocumentServer {
            get {
                return ResourceManager.GetString("DocumentServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLYOFFICE Document Server.
        /// </summary>
        public static string DocumentServerHdr {
            get {
                return ResourceManager.GetString("DocumentServerHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLYOFFICE Document Server is an online office suite comprising viewers and editors for texts, spreadsheets and presentations, compatible with all popular formats, enabling to co-edit, comment and communicate in real time..
        /// </summary>
        public static string DocumentServerText {
            get {
                return ResourceManager.GetString("DocumentServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation error.
        /// </summary>
        public static string ExistVersionErrorHdr {
            get {
                return ResourceManager.GetString("ExistVersionErrorHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove previously installed ONLYOFFICE components and try again.
        /// </summary>
        public static string ExistVersionErrorText {
            get {
                return ResourceManager.GetString("ExistVersionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware requirements.
        /// </summary>
        public static string HardwareRequirements {
            get {
                return ResourceManager.GetString("HardwareRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}40GB{1} Disk.
        /// </summary>
        public static string HardwareRequirementsDisc {
            get {
                return ResourceManager.GetString("HardwareRequirementsDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}6GB{1} Memory.
        /// </summary>
        public static string HardwareRequirementsMemory {
            get {
                return ResourceManager.GetString("HardwareRequirementsMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}2 Core{1} Processor.
        /// </summary>
        public static string HardwareRequirementsProcessor {
            get {
                return ResourceManager.GetString("HardwareRequirementsProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation failed.
        /// </summary>
        public static string InstallationErrorHdr {
            get {
                return ResourceManager.GetString("InstallationErrorHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured during the installation process..
        /// </summary>
        public static string InstallationErrorText {
            get {
                return ResourceManager.GetString("InstallationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ONLYOFFICE Control Panel.
        /// </summary>
        public static string InstallationPageHdr {
            get {
                return ResourceManager.GetString("InstallationPageHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLYOFFICE Installation Page.
        /// </summary>
        public static string InstallationPageTitle {
            get {
                return ResourceManager.GetString("InstallationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking ports.
        /// </summary>
        public static string InstallationProgressStep_CheckPorts {
            get {
                return ResourceManager.GetString("InstallationProgressStep_CheckPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete.
        /// </summary>
        public static string InstallationProgressStep_End {
            get {
                return ResourceManager.GetString("InstallationProgressStep_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking the operating system information.
        /// </summary>
        public static string InstallationProgressStep_GetOsInfo {
            get {
                return ResourceManager.GetString("InstallationProgressStep_GetOsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Community Server.
        /// </summary>
        public static string InstallationProgressStep_InstallCommunityServer {
            get {
                return ResourceManager.GetString("InstallationProgressStep_InstallCommunityServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Docker service.
        /// </summary>
        public static string InstallationProgressStep_InstallDocker {
            get {
                return ResourceManager.GetString("InstallationProgressStep_InstallDocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Document Server.
        /// </summary>
        public static string InstallationProgressStep_InstallDocumentServer {
            get {
                return ResourceManager.GetString("InstallationProgressStep_InstallDocumentServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Mail Server.
        /// </summary>
        public static string InstallationProgressStep_InstallMailServer {
            get {
                return ResourceManager.GetString("InstallationProgressStep_InstallMailServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebooting the server.
        /// </summary>
        public static string InstallationProgressStep_RebootServer {
            get {
                return ResourceManager.GetString("InstallationProgressStep_RebootServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the installstion.
        /// </summary>
        public static string InstallationProgressStep_Start {
            get {
                return ResourceManager.GetString("InstallationProgressStep_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files transfer.
        /// </summary>
        public static string InstallationProgressStep_UploadFiles {
            get {
                return ResourceManager.GetString("InstallationProgressStep_UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Configuration.
        /// </summary>
        public static string InstallationProgressStep_WarmUp {
            get {
                return ResourceManager.GetString("InstallationProgressStep_WarmUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install ONLYOFFICE.
        /// </summary>
        public static string InstallStepText {
            get {
                return ResourceManager.GetString("InstallStepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IP address.
        /// </summary>
        public static string IPAddressPlaceholder {
            get {
                return ResourceManager.GetString("IPAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Domain Name.
        /// </summary>
        public static string MailDomainPlaceholder {
            get {
                return ResourceManager.GetString("MailDomainPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Server.
        /// </summary>
        public static string MailServer {
            get {
                return ResourceManager.GetString("MailServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLYOFFICE Mail Server.
        /// </summary>
        public static string MailServerHdr {
            get {
                return ResourceManager.GetString("MailServerHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To configure Mail Server, the following DNS records are required:.
        /// </summary>
        public static string MailServerRequirementsHdr {
            get {
                return ResourceManager.GetString("MailServerRequirementsHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A record (used to point a domain to the IP address of the host where this docker image is deployed)..
        /// </summary>
        public static string MailServerRequirementsItem_1 {
            get {
                return ResourceManager.GetString("MailServerRequirementsItem_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer (RTP) record or a reverse DNS record (used to map a network interface (IP) to a hostname)..
        /// </summary>
        public static string MailServerRequirementsItem_2 {
            get {
                return ResourceManager.GetString("MailServerRequirementsItem_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLYOFFICE Mail Server is a full-featured solution developed on the base of the iRedMail package, containing the following components: Postfix, Dovecot, SpamAssassin, ClamAV, OpenDKIM, Fail2ban. It allows you to create and manage mailboxes using corporate domain name..
        /// </summary>
        public static string MailServerText {
            get {
                return ResourceManager.GetString("MailServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoreOS 647.0.0 (stable).
        /// </summary>
        public static string OperatingSystemCoreOS {
            get {
                return ResourceManager.GetString("OperatingSystemCoreOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fedora 20 (64-bit).
        /// </summary>
        public static string OperatingSystemFedora {
            get {
                return ResourceManager.GetString("OperatingSystemFedora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any other distributive with kernel version 3.19.
        /// </summary>
        public static string OperatingSystemOther {
            get {
                return ResourceManager.GetString("OperatingSystemOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubuntu 15.04 (64-bit).
        /// </summary>
        public static string OperatingSystemUbuntu {
            get {
                return ResourceManager.GetString("OperatingSystemUbuntu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the password.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum server requirements:.
        /// </summary>
        public static string ServerRequirements {
            get {
                return ResourceManager.GetString("ServerRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, the installation process is successfully completed!.
        /// </summary>
        public static string ServerSettingsFormDescHdr {
            get {
                return ResourceManager.GetString("ServerSettingsFormDescHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ServerSettingsFormHdr {
            get {
                return ResourceManager.GetString("ServerSettingsFormHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Control Panel is in beta stage and will be available soon. Enter your email below to be the first to learn about the release..
        /// </summary>
        public static string ServerSettingsFormText {
            get {
                return ResourceManager.GetString("ServerSettingsFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! Server connection established successfully..
        /// </summary>
        public static string SetupFormDescHdr {
            get {
                return ResourceManager.GetString("SetupFormDescHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation in progress....
        /// </summary>
        public static string SetupFormDescProgressHdr {
            get {
                return ResourceManager.GetString("SetupFormDescProgressHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ONLYOFFICE installation process may take a few minutes. Please wait..
        /// </summary>
        public static string SetupFormDescProgressText {
            get {
                return ResourceManager.GetString("SetupFormDescProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the information below to choose the ONLYOFFICE components that suit your needs best..
        /// </summary>
        public static string SetupFormDescText {
            get {
                return ResourceManager.GetString("SetupFormDescText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Options.
        /// </summary>
        public static string SetupFormHdr {
            get {
                return ResourceManager.GetString("SetupFormHdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community and Document Server will be installed by default. Select Mail Server if you need it..
        /// </summary>
        public static string SetupFormText {
            get {
                return ResourceManager.GetString("SetupFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We recommended that you install Mail Server together with other components. In case you decide to install it later you will need to remove all previously installed ONLYOFFICE components for successful installation..
        /// </summary>
        public static string SetupMailServerDesc {
            get {
                return ResourceManager.GetString("SetupMailServerDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software requirements.
        /// </summary>
        public static string SoftwareRequirements {
            get {
                return ResourceManager.GetString("SoftwareRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLYOFFICE Installer is distributed under the Apache license. The source code is listed on GitHub..
        /// </summary>
        public static string SourceDesc {
            get {
                return ResourceManager.GetString("SourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fork me on GitHub.
        /// </summary>
        public static string SourceLinkText {
            get {
                return ResourceManager.GetString("SourceLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH key.
        /// </summary>
        public static string SSHKey {
            get {
                return ResourceManager.GetString("SSHKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a SSH key.
        /// </summary>
        public static string SSHKeyPlaceholder {
            get {
                return ResourceManager.GetString("SSHKeyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to manually remove previously installed ONLYOFFICE components before you can continue installation..
        /// </summary>
        public static string UpdadeSetupOptionsDesc {
            get {
                return ResourceManager.GetString("UpdadeSetupOptionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the user name.
        /// </summary>
        public static string UserNamePlaceholder {
            get {
                return ResourceManager.GetString("UserNamePlaceholder", resourceCulture);
            }
        }
    }
}
