//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneClickInstallation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OneClickJsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OneClickJsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneClickInstallation.Resources.OneClickJsResource", typeof(OneClickJsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently only supports 64bit OS&apos;s.
        /// </summary>
        public static string ErrorInstallation1 {
            get {
                return ResourceManager.GetString("ErrorInstallation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported OS.
        /// </summary>
        public static string ErrorInstallation2 {
            get {
                return ResourceManager.GetString("ErrorInstallation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required ports are closed.
        /// </summary>
        public static string ErrorInstallation3 {
            get {
                return ResourceManager.GetString("ErrorInstallation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, set hostname for mail server.
        /// </summary>
        public static string ErrorInstallation4 {
            get {
                return ResourceManager.GetString("ErrorInstallation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command sudo not found.
        /// </summary>
        public static string ErrorInstallation5 {
            get {
                return ResourceManager.GetString("ErrorInstallation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while installing docker.
        /// </summary>
        public static string ErrorInstallation6 {
            get {
                return ResourceManager.GetString("ErrorInstallation6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kernel version not supported.
        /// </summary>
        public static string ErrorInstallation7 {
            get {
                return ResourceManager.GetString("ErrorInstallation7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To perform this action you must be logged in with root rights.
        /// </summary>
        public static string ErrorInstallation8 {
            get {
                return ResourceManager.GetString("ErrorInstallation8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create trial license. Invalid input parameter..
        /// </summary>
        public static string ErrorInstallationExternal1 {
            get {
                return ResourceManager.GetString("ErrorInstallationExternal1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create trial license.  An internal error is occured..
        /// </summary>
        public static string ErrorInstallationExternal2 {
            get {
                return ResourceManager.GetString("ErrorInstallationExternal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create trial license. The hostname has been assigned to another email address..
        /// </summary>
        public static string ErrorInstallationExternal3 {
            get {
                return ResourceManager.GetString("ErrorInstallationExternal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain name.
        /// </summary>
        public static string ErrorInvalidDomainName {
            get {
                return ResourceManager.GetString("ErrorInvalidDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string InstallationStepDoneMsg {
            get {
                return ResourceManager.GetString("InstallationStepDoneMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string InstallationStepErrorMsg {
            get {
                return ResourceManager.GetString("InstallationStepErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the process.
        /// </summary>
        public static string InstallationStepProcessMsg {
            get {
                return ResourceManager.GetString("InstallationStepProcessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string LoaderMsg {
            get {
                return ResourceManager.GetString("LoaderMsg", resourceCulture);
            }
        }
    }
}
